USE testdb
GO

ALTER TABLE WINE ADD IsDelete BIT NULL
GO

CREATE TRIGGER Wine_Delete
ON WINE
INSTEAD OF DELETE
AS
UPDATE WINE
SET IsDelete = 1
WHERE ID = (SELECT Id FROM deleted)
GO

SELECT ID, IsDelete FROM WINE WHERE ID > 99
GO

INSERT INTO WINE (ID, Title, Variety, Price, Country_id, Description_id) VALUES (101, 'Title','Variety',10,10,10)
GO

SELECT ID,IsDelete FROM WINE WHERE ID > 99
GO

DELETE FROM WINE WHERE ID = 101
GO

SELECT ID, IsDelete FROM WINE WHERE ID > 99
GO

DROP TRIGGER Wine_Delete
GO

DELETE FROM WINE WHERE ID = 101

ALTER TABLE WINE DROP COLUMN IsDelete
GO
