USE testdb
GO

CREATE PROCEDURE CursorProcedure AS

DECLARE @CURSOR CURSOR
SET @CURSOR  = CURSOR SCROLL
FOR
SELECT ID, Title, Variety FROM WINE WHERE Country_id > 5
OPEN @CURSOR
FETCH NEXT FROM @CURSOR
WHILE @@FETCH_STATUS = 0
BEGIN
FETCH NEXT FROM @CURSOR
END
CLOSE @CURSOR
GO

EXEC CursorProcedure
GO

DROP PROCEDURE CursorProcedure
