USE testdb
GO

SELECT Title, TasterName INTO #ExpensiveTaster FROM WINE JOIN (SELECT WINE_ID, TasterName FROM WINE_SOMMELIER JOIN SOMMELIER ON WINE_SOMMELIER.SOMMELIER_ID = SOMMELIER.ID) AS WS ON WINE.id = WS.WINE_ID WHERE Price > 15

SELECT * FROM #ExpensiveTaster
GO
