USE testdb
GO

SELECT Description FROM DESCRIPTION WHERE ID = 
(SELECT ID FROM [WINE] WHERE Variety = "Gamay" AND Price = 
	(SELECT AVG(Price) FROM [WINE] 
	JOIN (SELECT WINE_ID,TasterName FROM WINE_SOMMELIER JOIN SOMMELIER 
	ON WINE_SOMMELIER.SOMMELIER_ID = SOMMELIER.ID) AS WS ON WINE.ID = WS.WINE_ID GROUP BY TasterName 
	HAVING AVG(Price) = 
		(SELECT Price FROM [WINE] WHERE Price = 15 AND Country_id  = 8)))

GO
