USE testdb
GO
SELECT * FROM WINE W JOIN WINE_SOMMELIER WS ON W.ID = WS.WINE_ID WHERE WINE_ID IN (SELECT WINE_ID FROM WINE JOIN WINE_SOMMELIER ON WINE.ID=WINE_SOMMELIER.WINE_ID WHERE Variety = 'Aglianico')
GO

DELETE WS FROM WINE W JOIN WINE_SOMMELIER WS ON W.ID = WS.WINE_ID WHERE WINE_ID IN (SELECT WINE_ID FROM WINE JOIN WINE_SOMMELIER ON WINE.ID=WINE_SOMMELIER.WINE_ID WHERE Variety = 'Aglianico')
GO

SELECT * FROM WINE W JOIN WINE_SOMMELIER WS ON W.ID = WS.WINE_ID WHERE WINE_ID IN (SELECT WINE_ID FROM WINE JOIN WINE_SOMMELIER ON WINE.ID=WINE_SOMMELIER.WINE_ID WHERE Variety = 'Aglianico')
GO
