USE testdb;

WITH TCW(TN, NT)
AS
(
	SELECT TasterName, COUNT(Title)
	FROM WINE JOIN (SELECT WINE_ID,TasterName 
	FROM WINE_SOMMELIER JOIN SOMMELIER 
	ON WINE_SOMMELIER.SOMMELIER_ID = SOMMELIER.ID) AS WS 
	ON WINE.ID = WS.WINE_ID GROUP BY TasterName
)
SELECT tn,Nt AS 'Average number of taste' FROM TCW

GO
